version: "3.1"
# remember tabs matter
services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
